[package]
name = "blockus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.20"
serde_json = "1.0.107"
tinyjson = "2.5.1"
tokio = {version = "1.32.0", features=["full"]}
